name: Wealth-Engine UI Automation

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checks out project from github
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build and running the Maven test
      run: |
        mvn clean
        mvn  -Ddataproviderthreadcount=2 test
    - name: Uploading Artifact
      uses: actions/upload-artifact@v2
      if: always()
      with:
          name: Wealth Engine Automation Execution Report
          path: test-output/SparkReport
          retention-days: 30      
